# Generated by Django 5.0.1 on 2024-04-02 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0005_veiculo_ultimalavagem_alter_veiculo_alugado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origem', models.CharField(max_length=50)),
                ('Destino', models.CharField(max_length=50)),
                ('HorariodeEntrada', models.DateTimeField(default='')),
                ('HorariodeSaida', models.DateTimeField(blank=True, null=True)),
                ('quilometragemFinal', models.IntegerField(blank=True, null=True)),
                ('quilometragemInicial', models.IntegerField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('motivo', models.TextField(default='')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='veiculos.veiculo')),
            ],
        ),
    ]
