# Generated by Django 5.0.1 on 2024-04-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='cnh',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos_perfil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autorizacao.orgao'),
        ),
    ]
