# Generated by Django 5.0.1 on 2024-04-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0002_orgao_customuser_cnh_customuser_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('M', 'Motorista'), ('G', 'Gestor'), ('F', 'Funcionário')], default='G', max_length=1),
        ),
    ]
