# Generated by Django 5.0.1 on 2024-02-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_motorista_carro_delete_car_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crv', models.IntegerField()),
                ('cor', models.TextField()),
                ('placa', models.IntegerField()),
                ('marca', models.TextField()),
                ('modelo', models.TextField()),
                ('anoDeFabricacao', models.IntegerField()),
                ('tipoDeCombustivel', models.TextField()),
                ('capacidadeCombustivel', models.IntegerField()),
                ('quilometragem', models.FloatField()),
                ('estaDisponivel', models.BooleanField(default=True)),
                ('precisaAbastecer', models.BooleanField(default=False)),
                ('precisaDeManutencao', models.BooleanField(default=False)),
                ('temSeguro', models.BooleanField(default=False)),
                ('alugado', models.BooleanField(default=False)),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Carro',
        ),
        migrations.DeleteModel(
            name='Motorista',
        ),
    ]
