# Generated by Django 5.0.1 on 2024-04-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0002_orgao_customuser_cnh_customuser_foto_and_more'),
        ('veiculos', '0005_veiculo_ultimalavagem_alter_veiculo_alugado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autorizacao.orgao'),
        ),
    ]
