# Generated by Django 5.0.1 on 2024-02-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_veiculo_delete_carro_delete_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='crv',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.TextField(),
        ),
    ]
