# Generated by Django 5.0.1 on 2024-02-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_veiculo_crv_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ultimaLavagem',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='alugado',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.TextField(max_length=7),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='temSeguro',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipoDeCombustivel',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Gasolina/Alcool', 'Gasolina/Alcool'), ('Diesel', 'Diesel'), ('DieselS10', 'DieselS10'), ('Etanol', 'Etanol')], default=None, max_length=100),
        ),
    ]
