# Generated by Django 5.0.1 on 2024-02-06 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0004_alter_veiculo_crv_alter_veiculo_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoManutencao', models.CharField(choices=[('Troca de Oleo', 'Troca de Oleo'), ('Troca de Pneu', 'Troca de Pneu'), ('Troca Kit de Freio', 'Troca Kit de Freio'), ('Limpeza do radiador', 'Limpeza do radiador'), ('Outro', 'Outro')], default=None, max_length=100)),
                ('outraOpcao', models.CharField(blank=True, max_length=100, null=True)),
                ('quilometragemDoVeiculo', models.FloatField()),
                ('data', models.DateField()),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.veiculo')),
            ],
        ),
    ]
